from aiogram.dispatcher.filters.state import State, StatesGroup

class BotStates(StatesGroup):
    await_first = State()
    await_second = State()
    await_zapas = State()
    await_third = State()
    await_four = State()
    await_five = State()
    await_six = State()
    await_seven = State()
    await_eight = State()
    await_nine = State()
    await_ten = State()
    await_elev = State()
    await_twelve = State()
    await_thirty = State()
    # await_four = State()
    # await_four = State()
    # await_four = State()
    # await_four = State()
    # await_four = State()
    # await_four = State()
